source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Image-Cashing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic

  pod 'Kingfisher', '~> 3.0'

end
